### ISSUE TITLE
How to correctly handle ETag/Modified?

### ISSUE THREAD

**Issue by Shivelight** [kurtmckee/feedparser#200]
Currently, I'm relying on HTTP status code (304) but for a reason, the feed which I'm working on is redirecting my request with 301 status code thus the `status` attribute is set to 301. So my question is, is there a reliable way to detect if the feed is not modified?

**Comment by kurtmckee** [comment]
HTTP 301 is a permanent redirect to a new location. The feed *has* been modified because it is now located at a new URL.

If you update the URL you are requesting, it's possible that the site will return 304 on subsequent requests (though some sites and some software will fail to handle ETag/Last-Modified correctly).

I'm unaware of any way to perfectly know if a URL is unmodified.

**Comment by Shivelight** [comment]
Maybe I wasn't clear; an example would be better

```python
import feedparser

feed = feedparser.parse("https://www.archlinux.org/feeds/packages/")
etag = feed.etag

# no redirect
f1 = feedparser.parse("https://www.archlinux.org/feeds/packages/", etag=etag)
if f1.status == 304:
    print("f1 not modified", f1.status)
else:
    print("f1 modified", f1.status)

# redirect 301, notice the missing slash at the end of the url
f2 = feedparser.parse("https://www.archlinux.org/feeds/packages", etag=etag)
if f2.status == 304:
    print("f2 not modified", f2.status)
else:
    print("f2 modified", f2.status)

# >>> f1 not modified 304
# >>> f2 modified 301
```
Isn't f2 should print "not modified" here? or is it intended as to inform user about redirection?
Maybe having a boolean attribute to indicate if the feed content is modified is nicer.
...
As I'm writing this, I notice that I can rely on ETag returned regardless of the status attribute.
```python
# redirect 301, notice the missing slash at the end of the url
f3 = feedparser.parse("https://www.archlinux.org/feeds/packages", etag=etag)
if f3.etag == etag:
    print("f3 not modified", f3.status)
else:
    print("f3 modified", f3.status)

# >>> f3 not modified 301
```
I think my problem is solved. But I would like to see your comment on this as I'm not so familiar with feed (RSS?) and some of the HTTP part.

**Comment by kurtmckee** [comment]
The ETag for the URL that does not end in a slash was previously valid, but the Arch Linux server is no longer serving content at "/packages". It now only serves content from "/packages/". You must stop requesting content from "/packages" because it is returning an HTTP 301 Permanently Moved status.

Your problem is not solved by comparing the ETag you have against the redirected ETag -- the solution is to update your feed URL to match what the server is redirecting you to. Otherwise you're going to just keep making two HTTP requests and keep consuming unnecessary bandwidth for both you and Arch Linux.

The point of ETag is not for *you* to make comparisons, it's for the *server* to make a comparison and decide whether to send any content. If you keep requesting "/packages" with no slash, all of the benefit of ETag is lost and you have to write additional code to work around the root problem: the server doesn't want you to requires content from "/packages" anymore.

Switch to "/packages/" with a trailing slash, watch for permanent redirects in the future, and you won't have to manually compare ETags. =)

**Comment by Shivelight** [comment]
Thank you for your explanation, closing this.

**Comment by kurtmckee** [comment]
No problem! And happy new year!

**Comment by slidenerd** [comment]
In case someone is trying to do this by loading the URL separately with asyncio aiohttp while using feedparser to only parse the response text https://stackoverflow.com/questions/61746471/how-to-send-an-etag-or-last-modified-while-making-a-request-with-aiohttp-session
